#!/usr/bin/env bash
# Generated by `hal lifecycle spec render-verify`.
# Edit spec.md Success Criteria; re-render. Do not edit by hand.
set -uo pipefail
fails=0
total=0

crit_001() {
  # Full test suite passes
  nvim --headless -u tests/minimal_init.lua \
    -c "PlenaryBustedDirectory tests/ {minimal_init = 'tests/minimal_init.lua', sequential = true}" \
    -c "qa!" 2>&1 | tee /tmp/feats-refactor-test.log
  ! grep -E 'Tests Failed|Errors *: *[1-9]' /tmp/feats-refactor-test.log
}

crit_002() {
  # Coverage ≥ 80% (absolute, total) per luacov
  test -f luacov.report.out && \
    awk '/^Total/ {pct=$NF; gsub("%","",pct); exit !(pct+0 >= 80)}' luacov.report.out
}

crit_003() {
  # No shell-out site interpolates an unescaped path
  ! grep -rnE "(vim\.fn\.system|io\.popen|vim\.fn\.jobstart)\(.*\.\..*\)" lua/ \
    | grep -vE "shellescape|fnameescape|^[^:]+:[0-9]+:\s*--"
}

crit_004() {
  # No dynamic code execution from user-controlled input (loadstring/load/dofile/loadfile)
  ! grep -rnE "(loadstring|\bload\(|dofile|loadfile)" lua/ \
    | grep -vE "^[^:]+:[0-9]+:\s*--|-- audited:"
}

crit_005() {
  # No source file in lua/ exceeds 350 LOC (soft cap; exceptions documented in baseline.md)
  over=$(find lua -name '*.lua' -exec wc -l {} + | awk '$1 > 350 && $2 != "total" {print $2}')
  allowed=$(awk '/^ALLOWED_LARGE_FILES:/{flag=1; next} /^$/{flag=0} flag{print $2}' \
            docs/plans/0001-feats-refactor/baseline.md 2>/dev/null || true)
  diff <(echo "$over" | sort) <(echo "$allowed" | sort) | grep -q '^<' && exit 1 || exit 0
}

crit_006() {
  # CI workflow enforces test pass + 80% coverage gate
  grep -rE "(luacov|coverage).*(80|0\.80)" .github/workflows/ >/dev/null && \
  grep -rE "PlenaryBustedDirectory|busted" .github/workflows/ >/dev/null
}

crit_007() {
  # Public module surface unchanged (smoke load every existing top-level require path)
  nvim --headless -u tests/minimal_init.lua \
    -c "luafile docs/plans/0001-feats-refactor/scripts/smoke_require.lua" \
    -c "qa!"
}

main() {
  total=$((total + 1))
  out=$(crit_001 2>&1); rc=$?
  if [[ "$rc" -eq 0 ]]; then
    printf '[PASS] %s\n' 'Full test suite passes'
  else
    printf '[FAIL rc=%s expected=0] %s\n' "$rc" 'Full test suite passes'
    [[ -n "$out" ]] && printf '%s\n' "$out" | sed 's/^/        /'
    fails=$((fails + 1))
  fi
  total=$((total + 1))
  out=$(crit_002 2>&1); rc=$?
  if [[ "$rc" -eq 0 ]]; then
    printf '[PASS] %s\n' 'Coverage ≥ 80% (absolute, total) per luacov'
  else
    printf '[FAIL rc=%s expected=0] %s\n' "$rc" 'Coverage ≥ 80% (absolute, total) per luacov'
    [[ -n "$out" ]] && printf '%s\n' "$out" | sed 's/^/        /'
    fails=$((fails + 1))
  fi
  total=$((total + 1))
  out=$(crit_003 2>&1); rc=$?
  if [[ "$rc" -eq 0 ]]; then
    printf '[PASS] %s\n' 'No shell-out site interpolates an unescaped path'
  else
    printf '[FAIL rc=%s expected=0] %s\n' "$rc" 'No shell-out site interpolates an unescaped path'
    [[ -n "$out" ]] && printf '%s\n' "$out" | sed 's/^/        /'
    fails=$((fails + 1))
  fi
  total=$((total + 1))
  out=$(crit_004 2>&1); rc=$?
  if [[ "$rc" -eq 0 ]]; then
    printf '[PASS] %s\n' 'No dynamic code execution from user-controlled input (loadstring/load/dofile/loadfile)'
  else
    printf '[FAIL rc=%s expected=0] %s\n' "$rc" 'No dynamic code execution from user-controlled input (loadstring/load/dofile/loadfile)'
    [[ -n "$out" ]] && printf '%s\n' "$out" | sed 's/^/        /'
    fails=$((fails + 1))
  fi
  total=$((total + 1))
  out=$(crit_005 2>&1); rc=$?
  if [[ "$rc" -eq 0 ]]; then
    printf '[PASS] %s\n' 'No source file in lua/ exceeds 350 LOC (soft cap; exceptions documented in baseline.md)'
  else
    printf '[FAIL rc=%s expected=0] %s\n' "$rc" 'No source file in lua/ exceeds 350 LOC (soft cap; exceptions documented in baseline.md)'
    [[ -n "$out" ]] && printf '%s\n' "$out" | sed 's/^/        /'
    fails=$((fails + 1))
  fi
  total=$((total + 1))
  out=$(crit_006 2>&1); rc=$?
  if [[ "$rc" -eq 0 ]]; then
    printf '[PASS] %s\n' 'CI workflow enforces test pass + 80% coverage gate'
  else
    printf '[FAIL rc=%s expected=0] %s\n' "$rc" 'CI workflow enforces test pass + 80% coverage gate'
    [[ -n "$out" ]] && printf '%s\n' "$out" | sed 's/^/        /'
    fails=$((fails + 1))
  fi
  total=$((total + 1))
  out=$(crit_007 2>&1); rc=$?
  if [[ "$rc" -eq 0 ]]; then
    printf '[PASS] %s\n' 'Public module surface unchanged (smoke load every existing top-level require path)'
  else
    printf '[FAIL rc=%s expected=0] %s\n' "$rc" 'Public module surface unchanged (smoke load every existing top-level require path)'
    [[ -n "$out" ]] && printf '%s\n' "$out" | sed 's/^/        /'
    fails=$((fails + 1))
  fi
  echo "---"
  echo "$((total - fails))/$total criteria PASSED"
  if [[ "$fails" -gt 0 ]]; then exit 3; fi
  exit 0
}

main "$@"
