-- Test suite for shooter.filter_state module
local filter_state = require('shooter.filter_state')

describe('filter_state module', function()
  describe('module structure', function()
    it('exports expected functions', function()
      assert.is_function(filter_state.get_state_path)
      assert.is_function(filter_state.load_state)
      assert.is_function(filter_state.save_state)
      assert.is_function(filter_state.get_current_filter)
      assert.is_function(filter_state.set_current_filter)
      assert.is_function(filter_state.clear_current_filter)
      assert.is_function(filter_state.clear_all_filters)
      assert.is_function(filter_state.get_current_session_name)
      assert.is_function(filter_state.list_sessions)
      assert.is_function(filter_state.save_session)
      assert.is_function(filter_state.load_session)
      assert.is_function(filter_state.delete_session)
    end)
  end)

  describe('get_state_path', function()
    it('returns path in config directory', function()
      local path = filter_state.get_state_path()
      assert.is_truthy(path:match('shooter%.nvim'))
      assert.is_truthy(path:match('filter%-state%.json'))
    end)
  end)

  describe('load_state', function()
    it('returns table with current and sessions keys', function()
      local state = filter_state.load_state()
      assert.is_table(state)
      assert.is_table(state.current)
      assert.is_table(state.sessions)
    end)
  end)

  describe('get_current_filter', function()
    it('returns table', function()
      local filter = filter_state.get_current_filter()
      assert.is_table(filter)
    end)
  end)

  describe('list_sessions', function()
    it('returns array of strings', function()
      local sessions = filter_state.list_sessions()
      assert.is_table(sessions)
    end)
  end)

  describe('get_current_session_name', function()
    it('returns nil or string', function()
      local name = filter_state.get_current_session_name()
      if name ~= nil then
        assert.is_string(name)
      end
    end)
  end)
end)
