-- Test suite for shooter.core.project module
local project = require('shooter.core.project')

describe('project module', function()
  describe('module structure', function()
    it('exports expected functions', function()
      assert.is_function(project.has_projects)
      assert.is_function(project.get_projects_dir)
      assert.is_function(project.list_projects)
      assert.is_function(project.detect_from_path)
      assert.is_function(project.detect_from_cwd)
      assert.is_function(project.get_prompts_dir)
      assert.is_function(project.get_prompts_root)
      assert.is_function(project.pick_project)
    end)
  end)

  describe('get_prompts_root', function()
    it('returns root path when project is nil', function()
      local path = project.get_prompts_root(nil)
      assert.are.equal('plans/prompts', path)
    end)

    it('returns root path when project is empty string', function()
      local path = project.get_prompts_root('')
      assert.are.equal('plans/prompts', path)
    end)

    it('returns project path when project is specified', function()
      local path = project.get_prompts_root('myproject')
      assert.are.equal('projects/myproject/plans/prompts', path)
    end)

    it('includes project name in path', function()
      local path = project.get_prompts_root('dashboard')
      assert.is_truthy(path:match('projects/dashboard/'))
    end)
  end)

  describe('detect_from_path', function()
    it('returns nil for nil path', function()
      local result = project.detect_from_path(nil)
      assert.is_nil(result)
    end)

    it('returns nil for empty path', function()
      local result = project.detect_from_path('')
      assert.is_nil(result)
    end)

    it('returns nil for path not in projects folder', function()
      -- This test depends on git root, so we test the pattern matching
      local result = project.detect_from_path('/some/path/not/in/projects')
      assert.is_nil(result)
    end)
  end)

  describe('get_prompts_dir', function()
    it('returns absolute path', function()
      local path = project.get_prompts_dir(nil)
      assert.is_truthy(path:match('^/') or path:match('^%w:'))
    end)

    it('ends with plans/prompts for root', function()
      local path = project.get_prompts_dir(nil)
      assert.is_truthy(path:match('plans/prompts$'))
    end)

    it('includes project path for project', function()
      local path = project.get_prompts_dir('myproject')
      assert.is_truthy(path:match('projects/myproject/plans/prompts$'))
    end)
  end)
end)
