-- Tests for hidden_session module
local hidden_session = require('shooter.tmux.hidden_session')

describe('hidden_session module', function()
  describe('module structure', function()
    it('exports expected functions', function()
      assert.is_function(hidden_session.get_session_name)
      assert.is_function(hidden_session.session_exists)
      assert.is_function(hidden_session.ensure_session)
      assert.is_function(hidden_session.get_folder_name)
      assert.is_function(hidden_session.get_window_name)
      assert.is_function(hidden_session.find_window)
      assert.is_function(hidden_session.hide_pane)
      assert.is_function(hidden_session.restore_pane)
      assert.is_function(hidden_session.cleanup_session)
    end)
  end)

  describe('get_session_name', function()
    it('returns the hidden session name', function()
      local name = hidden_session.get_session_name()
      assert.are.equal('shooter-hidden-panes', name)
    end)
  end)

  describe('get_window_name', function()
    it('combines folder and pane name', function()
      local name = hidden_session.get_window_name('myproject', 'test1')
      assert.are.equal('myproject-test1', name)
    end)

    it('handles special characters in names', function()
      local name = hidden_session.get_window_name('my-project', 'my-pane')
      assert.are.equal('my-project-my-pane', name)
    end)
  end)

  describe('get_folder_name', function()
    it('returns a non-empty string', function()
      local folder = hidden_session.get_folder_name()
      assert.is_string(folder)
      assert.is_true(#folder > 0)
    end)
  end)
end)
